### PR TITLE
Networkx 2.0 compatibility fix by @Erotemic

### PR DESCRIPTION
**Pull request by ewels**
Fix suggested by @Erotemic in #73.

I'm the author of a tool that was affected by this problem through a web of several dependencies, see https://github.com/ewels/MultiQC/pull/561

Thanks!

Phil

### CODE REVIEW

**Comment by gtaylor** [comment]
Thanks, @ewels!

Fixes #73.

**Comment by ewels** [comment]
Hi @gtaylor,

Any idea when the next release will go out? It would be great if this fix could hit PyPI before nextworkx 2.0 comes out of beta..

Phil

**Comment by ewels** [comment]
Hi @gtaylor,

The new networkx 2.0 release is now live, so all installations of colormath (and downstream tools) will now be broken until the next release goes out..

Let me know if there's anything that I can do to help!

Cheers,

Phil

**Comment by Erotemic** [comment]
Thanks for merging this for me!

**Comment by Jaza** [comment]
Hi @gtaylor, new release of colormath would be great, latest stable (2.1.1) is broken on CircleCI due to this problem.

**Pull request merged**
