### PR TITLE
Add AppleRGBColor

### PR DESCRIPTION
**Pull request by janek-warchol**
First of all: very nice library, thanks a lot for publishing it!

I need to do some transformations from sRGB to Apple RGB, so why not add AppleRGBColor class?

I have copied transformation matrices from
http://www.brucelindbloom.com/Eqn_RGB_XYZ_Matrix.html#WSMatrices
and the other constants (illuminant and gamma) from
http://www.brucelindbloom.com/index.html?WorkingSpaceInfo.html#ColorSets

As far as I can tell this is the same Apple RGB space as is available in
Adobe Photoshop.

I hope I did this right - I'm pretty new to color space transformations... Let me know if something's wrong.

Thanks!

### CODE REVIEW

**Comment by gtaylor** [comment]
Hello @janek-warchol ! Thanks for sending this in.

This is looking pretty good. If I can just get a test case for XYZ to/from Apple RGB, we'll go on ahead and merge this.

Here's a link to the XYZ to RGB case for Adobe RGB: https://github.com/janek-warchol/python-colormath/blob/master/tests/test_color_objects.py#L98

If you have any additional ideals for cases to cover, feel free to toss them in as well.

Thanks for the pull request!

**Comment by janek-warchol** [comment]
Hello,

sure! I'm running into some issues with roundtrip conversion producing unexpected results - probably I'm doing something wrong - so it may take me a day or two to produce the test case, but I'll get back to you :-)

**Comment by janek-warchol** [comment]
Hi again @gtaylor !  The test is done.

**Comment by gtaylor** [comment]
Excellent. I haven't had a ton of time to test this myself, but I'm going to go on ahead and merge this so we can get it in other people's hands as well. It passes the eyeball test, and we can iterate as need be prior to a full PyPi release.

I'm without internet at home, pending Comcast not being crappy. Once that gets set up, I should be able to get the release cut.

**Comment by janek-warchol** [comment]
Great, thanks!

**Pull request merged**
